title: My Portfolio
email: your.email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal portfolio website where I showcase my projects, internships, and essays.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter_username
github_username: yourusername

markdown: kramdown
theme: jekyll-theme-minima

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
